name: CI Pipeline SonarQube-Lab

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build, Test e SonarQube Scan
        run: >
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -B
          -Dsonar.projectKey=DanielDeAzevedoCordeiro1_sonarqube-lab
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
          -Dsonar.login=${{ env.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_REPO_LAB_SONARQUBE }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_REPO_LAB_SONARQUBE }}

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: target/site/jacoco
          retention-days: 30

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports
          path: target/surefire-reports/*.xml
          retention-days: 30